### ISSUE TITLE
LatestHandshakeTime is set to Unix epoch zero, not zero-valued time.Time as documented

### ISSUE THREAD

**Issue by cespare** [mdlayher/wireguardctrl#24]
wgtypes.Peer.LastHandshakeTime docs say:

```
    // A zero-value time.Time indicates that no handshake has taken place with
    // this peer.
```

However, empirically it seems to use the zero Unix time (i.e., `time.Unix(0, 0)`), not `time.Time{}`.

**Comment by mdlayher** [comment]
Are you using the Linux kernel (genetlink interface) implementation?

Sounds like an oversight on my part. I'll compare what the userspace device and kernel interface send for this situation, but I suspect it'd make sense to make the value a zero-value time.Time since January 1, 1970 is also unlikely to come up in practice.

**Comment by cespare** [comment]
> Are you using the Linux kernel (genetlink interface) implementation?

Yep.

> Sounds like an oversight on my part. I'll compare what the userspace device and kernel interface send for this situation, but I suspect it'd make sense to make the value a zero-value time.Time since January 1, 1970 is also unlikely to come up in practice.

Yeah, the solution in #25 is what I had in mind. Thanks.

**Comment by mdlayher** [comment]
Thanks for the bug report! Let me know if you find anything else that seems off. I'm happy to continue making improvements to both the internals and ergonomics of this package.
